name: Update Repositories

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout actions repository
        uses: actions/checkout@v2

      - name: List all repositories
        run: |
          REPOSITORIES=$(curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" https://api.github.com/orgs/${{secrets.GIT_ORG_NAME}}/repos | jq -r '.[] | .ssh_url')

      - name: Update workflows in repositories
        run: |
          for repo in $REPOSITORIES; do
            git clone $repo
            cp -r .github/actions/* $repo/.github/workflows
            cd $repo
            git config --global user.email "github-actions-bot@example.com"
            git config --global user.name "GitHub Actions Bot"
            git add .
            git commit -m "Build: bot update workflows"
            git push
            cd ..
            rm -rf $repo
          done
