name: Update Repositories

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout actions repository
        uses: actions/checkout@v2

      - name: add ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_SECRET }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: User Repos
        run: |
          curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" https://api.github.com/user/repos

      - name: Filtered repos
        run: |
          curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" https://api.github.com/user/repos | jq -r '.[] | select(.name | contains("gym-api")) | .ssh_url'

      - name: List all repositories
        run: |
          REPOSITORIES=$(curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" https://api.github.com/user/repos | jq -r '.[] | select(.name | contains("gym-api")) | .ssh_url')
          for repo in $REPOSITORIES; do 
            git clone $repo cloned
            cp -rT .github/actions/* cloned/.github/workflows
            cd cloned
            git config --global user.email "alemassajr@hotmail.com"
            git config --global user.name "Alessandro-Massarotti-Jr"
            git add .
            git commit -m "Build: bot update workflows"
            git push
            cd ..
            rm -rf cloned
          done
