name: Update Repositories

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout actions repository
        uses: actions/checkout@v2

      - name: Get Repositories
        run: |
          REPOSITORIES=$(curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" "https://api.github.com/user/repos" | jq -r '.[] | select(.name | contains("gym-api")) | .ssh_url')

      - name: Print Repositories
        run: |
          echo "$REPOSITORIES"

      - name: Update workflows in repositories
        run: |
          for repo in $REPOSITORIES; do
            echo "Cloning repository: $repo"
            git clone $repo || { echo "Error cloning repository: $repo"; exit 1; }

            echo "Copying workflows to repository: $repo"
            cp -r .github/actions/* "$(basename $repo)/.github/workflows" || { echo "Error copying workflows to repository: $repo"; exit 1; }

            echo "Accessing repository directory: $repo"
            cd "$(basename $repo)" || { echo "Error accessing repository directory: $repo"; exit 1; }

            echo "Configuring user email for commits"
            git config --global user.email "github-actions-bot@example.com"
            git config --global user.name "GitHub Actions Bot"

            echo "Adding changes to commit"
            git add . || { echo "Error adding changes to commit: $repo"; exit 1; }

            echo "Committing changes"
            git commit -m "Build: bot update workflows" || { echo "Error committing changes: $repo"; exit 1; }

            echo "Pushing changes"
            git push || { echo "Error pushing changes: $repo"; exit 1; }

            echo "Returning to previous directory"
            cd .. || { echo "Error returning to previous directory: $repo"; exit 1; }

            echo "Removing cloned repository: $repo"
            rm -rf "$(basename $repo)" || { echo "Error removing cloned repository: $repo"; exit 1; }
          done
