name: Update Repositories

run-name: Update directories action started by ${{github.actor}}

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout actions repository
        uses: actions/checkout@v2
      - name: set up ssh key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_SECRET }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "bot"

      - name: List all repositories
        run: |
          REPOSITORIES=$(curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN  }}" https://api.github.com/user/repos | jq -r '.[] | select(.name | contains("gym-api")) | .ssh_url')
          for repo in $REPOSITORIES; do 
            git clone $repo cloned
            if [ ! -d "cloned/.github/workflows" ]; then
              mkdir -p cloned/.github/workflows
            fi
            cp -r .github/actions/* cloned/.github/workflows
            cd cloned
            git checkout develop
            if ! git diff --quiet --exit-code; then
              git add .
              git commit -m "Build(github): bot update workflows"
              git push origin main
            fi
            cd ..
            rm -rf cloned
          done
